# Generated by Django 5.2.3 on 2025-07-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.distro')),
            ],
        ),
    ]
