# Generated by Django 5.2.3 on 2025-07-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_patches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patches',
            new_name='Patch',
        ),
    ]
