# Generated by Django 5.2.3 on 2025-07-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_patches_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='distro',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='distros/'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='photo',
            field=models.ImageField(upload_to='patches/'),
        ),
    ]
