# Generated by Django 5.2.3 on 2025-07-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_distro_photo_alter_patch_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distro',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main_app/distros/'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='photo',
            field=models.ImageField(upload_to='main_app/patches/'),
        ),
    ]
