# Generated by Django 5.2.3 on 2025-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_patch_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distro',
            name='photo',
            field=models.ImageField(default=1, upload_to='main_app/distros/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patch',
            name='photo',
            field=models.ImageField(upload_to='main_app/patches/'),
        ),
    ]
